version: "3.9"

services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_SSL: off
    ports:
      - "3307:3306"
    volumes:
      - mysql-persistence:/var/lib/mysql

  app:
    build:
      dockerfile: Dockerfile
    working_dir: /workspace
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      # Database connection variables for PHP app
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: ""
  mail:
    image: axllent/mailpit
    ports: [2080:8025]

volumes:
  mysql-persistence:
